[process_config]
my_as = 2
router_id = "1.1.1.1"
next_hop_ip = "10.0.0.1"
default_local_preference = 100
default_med = 0
[process_config.capabilities_config]
route_refresh_prestandard = false
route_refresh = false
enhanced_route_refresh = false
extended_4byte_asn = true
[process_config.capabilities_config.multi_protocol_extensions_config]
ipv4_unicast = true
ipv4_multicast = false
ipv4_vpn = false
ipv6_unicast = false
ipv6_multicast = false
ipv6_vpn = false



[[net_advertisements_config]]
prefix = "1.1.1.1/32"

[[net_advertisements_config]]
prefix = "10.1.0.0/24"

[[neighbors_config]]
ip = "10.0.0.24"
as_num = 1
hello_time = 30
hold_time = 90
